GET http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRkYjhlMjFjLWVjNDYtNGE3YS1iYzcwLWM3N2E5Y2EyMGQ3NSIsIm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc4MDU5MTY4NSwiZXhwIjoxNzgwNTk1Mjg1fQ.gJwOw5pCZthNWa1g1j4OfMKH52WysFhy2OqD51DQrx4

###
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "12345678"
}

###
POST http://localhost:3000/api/auth/register
Accept: application/json
Content-Type: application/json

{ 
  "name": "Jhovana",
  "email": "jhova@mail.com",
  "password": "12345678",
  "role": "CUSTOMER"
}

###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRkYjhlMjFjLWVjNDYtNGE3YS1iYzcwLWM3N2E5Y2EyMGQ3NSIsIm5hbWUiOiJhZG1pbiIsImlhdCI6MTc3OTk3NzUxNywiZXhwIjoxNzc5OTgxMTE3fQ.buw5MUisq39w695tK0WcRhIv0AvX9tGA8ZHkuK592aQ