GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZGI4ZTIxYy1lYzQ2LTRhN2EtYmM3MC1jNzdhOWNhMjBkNzUiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzc4NzAxMjg1LCJleHAiOjE3Nzg3MDQ4ODV9.eDW7ne8AIalxsyL-mpOMKeOFTHF4lW9_kzvcB-VZK0s

###
POST http://localhost:3000/users
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@mail.com",
  "password": "123456",
  "role": "ADMIN"
}

###
GET http://localhost:3000/users/5600ac09-fae6-48d6-a318-b51caa514e48

###
PATCH http://localhost:3000/users/7803ac09-fae6-48d6-a318-b51caa514e48
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@mail.com",
  "password": "12345678",
  "role": "ADMIN"
}

###
DELETE http://localhost:3000/users/7803ac09-fae6-48d6-a318-b51caa514e48