GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRkYjhlMjFjLWVjNDYtNGE3YS1iYzcwLWM3N2E5Y2EyMGQ3NSIsIm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3OTk5NzQ0MCwiZXhwIjoxNzgwMDAxMDQwfQ.wQVz5ZMFMc5phAdiDVvCkGMIG3FalKjUNRfTv-OmseE

###
POST http://localhost:3000/users
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@mail.com",
  "password": "123456",
  "role": "ADMIN"
}

###
GET http://localhost:3000/users/5600ac09-fae6-48d6-a318-b51caa514e48

###
PATCH http://localhost:3000/users/ddb8e21c-ec46-4a7a-bc70-c77a9ca20d75
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@mail.com",
  "password": "12345678",
  "role": "ADMIN"
}

###
DELETE http://localhost:3000/users/7803ac09-fae6-48d6-a318-b51caa514e48